apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo '<!DOCTYPE html>
            <html lang="he">
            <head>
                <meta charset="UTF-8" />
                <title>שלום זה תומר</title>
                <style>
                    body {
                        background: linear-gradient(135deg, #89f7fe 0%, #66a6ff 100%);
                        font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
                        color: #fff;
                        text-align: center;
                        padding: 50px;
                        direction: rtl;
                    }
                    .container {
                        background: rgba(0, 0, 0, 0.3);
                        border-radius: 15px;
                        padding: 40px;
                        max-width: 600px;
                        margin: 0 auto;
                        box-shadow: 0 8px 32px rgba(0, 0, 0, 0.2);
                    }
                    h1 {
                        font-size: 3rem;
                        margin-bottom: 20px;
                    }
                    p {
                        font-size: 1.5rem;
                        letter-spacing: 0.05em;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h1>שלום זה תומר</h1>
                    <p>ברוכים הבאים לעמוד הניג\'ינקס שלי!</p>
                </div>
            </body>
            </html>' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
